# Generated by Django 5.1.3 on 2025-02-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('folder_path', models.TextField()),
                ('geography', models.TextField(blank=True, null=True)),
                ('season', models.TextField(blank=True, default='all', null=True)),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('cooking_time', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('total_yield', models.TextField(blank=True, null=True)),
                ('special_equipment', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recipes',
                'unique_together': {('title', 'folder_path')},
            },
        ),
    ]
